// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvSZYhIxkj-IsLxltP1qA2tmS27MF-Suw',
    appId: '1:135592115838:web:90b024381cd9da09c5e22f',
    messagingSenderId: '135592115838',
    projectId: 'synergy-0',
    authDomain: 'synergy-0.firebaseapp.com',
    storageBucket: 'synergy-0.firebasestorage.app',
    measurementId: 'G-R571WHZ77D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwKL0Sf0bw_-FgwtJWQ18cam2q6vQeqkE',
    appId: '1:135592115838:android:1ec8b3386ec32134c5e22f',
    messagingSenderId: '135592115838',
    projectId: 'synergy-0',
    storageBucket: 'synergy-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBUX-SK3imvBllBFKVn10ra-l0TRGsaU',
    appId: '1:135592115838:ios:35fba75837d6f2e4c5e22f',
    messagingSenderId: '135592115838',
    projectId: 'synergy-0',
    storageBucket: 'synergy-0.firebasestorage.app',
    iosBundleId: 'com.example.pingstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeBUX-SK3imvBllBFKVn10ra-l0TRGsaU',
    appId: '1:135592115838:ios:35fba75837d6f2e4c5e22f',
    messagingSenderId: '135592115838',
    projectId: 'synergy-0',
    storageBucket: 'synergy-0.firebasestorage.app',
    iosBundleId: 'com.example.pingstar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvSZYhIxkj-IsLxltP1qA2tmS27MF-Suw',
    appId: '1:135592115838:web:0d5265625466b287c5e22f',
    messagingSenderId: '135592115838',
    projectId: 'synergy-0',
    authDomain: 'synergy-0.firebaseapp.com',
    storageBucket: 'synergy-0.firebasestorage.app',
    measurementId: 'G-Q1T5G01GKX',
  );
}
